### ISSUE TITLE
Console Windows Host - spawned every injection

### ISSUE THREAD

**Issue by joshdodger197** [kyleavery/inject-assembly#1]
First off - great tool. Incredible contribution to the community. I just wanted to note that Console Windows Host (conhost.exe) spawns as a child process of whatever process is being injected. 

My brain is too small to resolve this issue myself.  Sorry I'm dumb.

**Comment by kyleavery** [comment]
Good point! I forgot to mention that if you are injecting into a process that does not already have a console associated with it, conhost.exe will be spawned as a child for the duration of the execution. Tools like [inlineExecute-Assembly](https://github.com/anthemtotheego/InlineExecute-Assembly) do the same thing if they are executed in a process without an associated console.

Although not my first choice, this is expected behavior.

**Comment by joshdodger197** [comment]
Thanks for the follow-up Kyle!
